unit04/w11_d02/lecture/rails_101/my_app/config/routes.rb
Rails.application.routes.draw do
  get '/welcome', to: 'welcome#index'
  get '/about', to: 'about#index'
  resources :people
end

unit04/w11_d02/lecture/rails_101/my_app/app/models/person.rb
class Person < ApplicationRecord
end

unit04/w11_d02/lecture/rails_101/my_app/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    #render text: 'About me!'
  end
end

unit04/w11_d02/lecture/rails_101/my_app/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    if params[:id] == "1"
      render text: "Person #{params[:id]} loves Ruby on Rails!"
    else
      render text: 'Everyone loves Ruby on Rails!'
    end
  end

  def new
      #render text: 'Welcome!'
  end

  def create
    @person = Person.new(params[:person])
    @person.save

    redirect_to @person
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(
      :username, :first_name, :last_name
    )
  end

end

unit04/w11_d02/lecture/rails_101/my_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #render text: 'Welcome!'
  end
end

unit04/w11_d02/lecture/rails_101/my_app/app/views/about/index.html.erb
<h1>My About page!</h1>

unit04/w11_d02/lecture/rails_101/my_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

unit04/w11_d02/lecture/rails_101/my_app/app/views/people/index.html.erb
<h1>My People page!</h1>

unit04/w11_d02/lecture/rails_101/my_app/app/views/people/new.html.erb
<h1>New Person Page!</h1>
<br>
<form <%= link_to 'People', people_path %> >
<label>username</label>
<input type="text" name="person[username]" />
<label>first name</label>
<input type="text" name="person[first_name]" />
<label>last name</label>
<input type="text" name="person[last_name]" />
<button>Submit</button>
</form>

unit04/w11_d02/lecture/rails_101/my_app/app/views/welcome/index.html.erb
<h1>Welcome HTML Page!</h1>
<%= link_to 'About', about_path %>
<br>
<%= link_to 'People', people_path %>
<br>
<%= link_to 'New Person', people_path %>